### ISSUE TITLE
Yolov2-tiny (COCO)

### ISSUE THREAD

**Issue by michalek-marcin** [keijiro/TinyYOLOv2Barracuda#4] opened 2021-02-26 07:48 UTC
Hi,

I have a problem. I was struggling with the conversion from darknet to ONNX for several days, but today I finally succeed.

I have two versions of yolov2-tiny: voc (20 classes) and coco (80 classes) converted by me.
VOC model works out of the box, but COCO doesn't.
I changed:

ClassCount and _labels in Config file
CLASS_COUNT and anchors in Common.hlsl
model assigned to TinyYOLOv2 asset.
Here is my COCO model:
https://drive.google.com/file/d/1epFgd3Sx0NikGB-Y9oHsVWlACxclmjnL/view?usp=sharing

Could you @keijiro try to check my model and tell me what else do I need to change?

**Comment by keijiro** [comment] 2021-02-26 08:53
I think you should change `ClassCount` in `Config.cs` too. https://github.com/keijiro/TinyYOLOv2Barracuda/blob/main/Assets/Script/Config.cs#L8

**Comment by keijiro** [comment] 2021-02-26 08:56
Ah, you also changed it. Sorry. I overlooked it.

Could you share the entire project?

**Comment by michalek-marcin** [comment] 2021-02-26 11:08
@keijiro I sent you an email with link to my project.

**Comment by keijiro** [comment] 2021-02-28 05:59
I'm closing this issue now as assuming the issue is in the training process. Please feel free to reopen it for further problems on the inference side.

**Closed as completed by keijiro** 2021-02-28 05:59 UTC
Labels: question

**Comment by michalek-marcin** [comment] 2021-03-01 09:22
I finally found reason: https://github.com/allanzelener/YAD2K/issues/65. I had to correct one script which convert my darknet model to keras.

**Comment by Ademord** [comment] 2021-06-09 14:40
@michalek-marcin could you share your coco model and the class config.cs ?
